@startuml
'https://plantuml.com/class-diagram
class Netflix{
}
class Cuenta {
    - nombreDelUsurio: String
}
class Suscripcion {
    + adquirirUnaSuscripcion()
}

Netflix --> "*" Cuenta
Cuenta -> "1" Suscripcion
Netflix --> "*" Pelicula
Netflix --> "*" Suscripcion
Netflix --> "*" Serie
Suscripcion --> "1" MiLista
Pelicula --> "n" Generos
Serie --> "n" Capitulos


@enduml