@startuml
'https://plantuml.com/class-diagram

class Autolavado{
// Aqui va el registro de lavadas
    - lavadasRealizadas : lavada[n]
    - gananciasTotales : double
    + imprimirInformacionGeneral : String
}

Autolavado --> "*" Lavada: - lavada

class Lavada {
    - tipoDeLavada: TipoDeLavada
    - precio: double

}
Lavada --> "*" Cliente: - cliente
class Cliente{
    - nombre: String
    - dineroDisponible: double
}

class TipoDeLavada{
    - general: String
    - aMano: String
    - ecologica: String
}


@enduml