@startuml
class Botella{
- color: String
- capacidadMáximaLitros: double
- capacidadActualLitros: double
- material: Material
- pesoOnzas: double
- tapado: bolean

+ llenarCiertaCantidad(cantidadALlenar: double)
+ llenarPorCompleto()
+ llenarConOtraBotella(otraBotella: Botella)
- DarMasDeLoQueRecibe()
+ vaciarCiertaCantidad()
- seRebasaLaCapacidad()
+ vaciarPorCompleto()
- estaTapado()
+ destapar()
+ tapar()
+ imprimirCapacidadActual()
}
@enduml