@startuml
'https://plantuml.com/class-diagram

class Empresa {
}

Empresa --> "*" Cliente
Empresa --> "*" Turno
Cliente "1"<- Turno
Turno --> TipoDeTurno
Turno --> Fecha
enum TipoDeTurno {
    URGENTE
    NORMAL
}




@enduml