@startuml
Title Diagrama de clases:

class Luz {
    - cantidadDeLuz : double
    + receptarLuz()
    + getLuz()
    + notificarCambio()
}
class Foco {
    + encender()
    + apagar()
}
class Umbral {
    - umbral : double
    + verificarUmbral()
}
class Sensor {
    + sensar()
    + actualizar()
}


Luz <--> Sensor
Luz --R Foco
Sensor --R Umbral
Umbral --U Foco

@enduml