@startuml

class Vuelo{
- companiaDelVuelo: String
- origen: String
- destino: String
- fecha: String
- hora: String
- asientosTotal: int
- cantidadDeAsientosPremium: int
- cantidadDeAsientosEconomica: int
- ticketsPremium: Ticket[cantidadDeAsientosPremium]
- ticketsEconomica: Ticket[cantidadDeAsientosEconomica]
}

class Ticket{
- pasajero: String
- precio: double
- vendido: boolean
+ comprar()
+ devolver()

}


@enduml