@startuml

class Ticket {
- tipoDeTicket: String
- numeroDeAsiento: int
- fechaDeVuelo: int //Imprimir no mas
- pasajero: String
- origen: String //Imprimir no mas
- destino: String //Imprimir no mas
- vendido: boolean
- cancelado: boolean
- libre: boolean


+ comprarTicket()
+ cancelarTicket()

}

class Vuelo{
ticketsClaseEconomica[n]: Ticket //mal escrito
ticketsClasePremium[n]: Ticket
}
@enduml