@startuml
'https://plantuml.com/class-diagram


Netflix --> Cuenta
Netflix --> Pelicula
Pelicula --> Genero
Netflix --> Serie
Serie --> Capitulo
Cuenta --> suscripcion
Cuenta --> Perfil
Perfil --> List

class Netflix {
}
enum suscripcion{
    BASICO
    ESTANDAR
    PREMIUM
    SIN_PAGAR
}
enum Genero {
    FICCION
    ROMANCE
    DRAMA
    MISTERIO
    COMEDIA
}


@enduml