@startuml
'https://plantuml.com/class-diagram

class Armario {
}
Armario --> PrendaDeVestir
PrendaDeVestir <|- Camiseta
Pantalon -|> PrendaDeVestir
Tanga -u-|> PrendaDeVestir
class Armario {
    +guardar()


}

class PrendaDeVestir {
    - color : String
    -
}

@enduml