@startuml
'https://plantuml.com/class-diagram


Netflix --> Cuenta
Netflix --> Pelicula
Netflix --> Serie
Cuenta --> Suscripcion
Suscripcion --> Perfil
Perfil --> List

class Netflix {
}
enum Suscripcion{
    BASICO
    ESTANDAR
    PREMIUM
    SIN_PAGAR
}
class Pelicula {
    - genero: String
}
class Serie {
    - capitulos : int [n]
}
class List {
    - peliculasPorVer : Pelicula[n]
    - seriesPorVer : Serie [n]

}


@enduml